language: go

env:
  secure: "oRUfXQ4ShSrgk9MdBQ5i/SFxtfEaNbqeJocl+D9+RSq73gWcZbwJDVgTExxessLypHxnTDSSWdCi9dMkEiwiSE0HmwXAWhDcYTrWqT1kQllMmEX80qD4ZpSKNUUl8OrSjf1kkvxwFaBn9gfvyK1ZpF55Yjf/DphR0x3u/ct/iRoEyokGjqzrio/HQc/CJ66SVYGWh614X0wol/Z3RrniIFkxL8OQzAPjMBDqiqCpuXvQsBMh4kbUel5Gf8v3uvwHRxIIO+EMk41X0BGQX5/kcongxL38a9rS7PjWX5IWaLn0UYAINre20w9L/Rmsa0pT+r6gXRQx7PxcOYSittrtBBa3WDUWtxuQ7XOrLlKGC48TdCAEGephw0Wcp6zvGC913wXkvQ/rg97rfDstxVKZK+MjdqPvpA/ZfBzJtfQTsX/dWWwCEWz+H5WZizv585D+oCyexSMOlUPEE+KGRMqcLtGV/+0CQ4KHa7ka1STbZMqDmpjkf6ubSdE8RhWrXQn3/oVU6PUzRUvko0K56lH7Ggc9ofLy3fDN4eaLPLxYm9mARS0+SuCDSGlz80lfXd2FQRtYaC8Vy4gDfkUgJD8v+mT+g0f8G8eYrxEOMgsGl2iLPLisKDEIaBP/batotQ4JIKQAEho56Qzvq1BUoO54xDkeZpS6XYWdVIgQGnjVSTg="

deploy:
  provider: releases
  api_key: 
    secure: "iumDvYQyMvTdD2AHxFDIVpixE7GK5VhCDo4wqkH9s3lmLIXTw2LPgUq4tx73aV7PGKskvWpILq87bh6t1AlFYnk/0VF12zMQWujsvh/iSdyCVvraobhYjiwQyHkFSoTBZ0xpwVImqRhF/AcAP/zwCTAGZMZMSm8xZucqkPaj02o8xgCKgPyDwv/IPo2Iiy6LmLbYeWBFScMtEyPqxjoKL5lL3b6e1W0esbJvPhzWQvTn2IBB8Ntm5hBBcqzG+/K3dNLpRTefX1xJlo2c5ZFT+KPFqIvNviNne7OhlX+NGZ33jUXVDPF4Lk6jLr49QnlTbqz8CKp3QzlpzOs+eF+2BBl5Gc1vJ0thmZ/TEujYD0rGzwDQ6nCVC6/VBbPiYhmQigk+AYFfxgutzHIfnuuySEoi5KOLNINtppwUTYjuxUv+YkQTUswCTa2MBoL0ZfAkdyrbBkGRL78sPRDRLK6KFXqz0Bk+pQdS0PebNclqaPnEML1jQYdRBgBQ0uFGcfOLkmIDr/L7icSif4uDrwaE1GnhHeloUOlaTSc63BSw1GdC+iYiGi8/TNg0Nw5co+M6Ii/Wuea9ngayAhVgNC64hV1giQEPPTfuS3EAxBf4ytybuqH3p+VtqD3ES97OqGGup4PHHQVPEdc6bzsD2aThLCeqpS/O9By9PiQcku+L+oo="
  file: bin/squid-exporter
  skip_cleanup: true
  on:
    tags: true
